# Generated by Django 5.0.2 on 2024-02-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfood', '0002_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('number_of_people', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Stol buyurtma',
                'verbose_name_plural': 'Stol buyurtmalar',
            },
        ),
    ]
