# Generated by Django 5.0.2 on 2024-02-09 05:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfood', '0003_booktable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='phone',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message="Telefon raqamingizni to'g'ri kiriting. Masalan: +998901234567 yoki 901234567", regex='^\\+?998?\\d{9,15}$')]),
        ),
    ]
